from league import *
from club import Club

#ligue 1
ligue_1 =League('ligue-1','FR1',2022,20,'Ligue_1')

Ajaccio = Club('AC Ajaccio', ligue_1)
Angers = Club('Angers SCO', ligue_1)
Auxerre = Club('AJ Auxerre', ligue_1)
Brest = Club('Stade Brestois 29', ligue_1)
Clermont = Club('Clermont Foot 63', ligue_1)
Lens = Club('RC Lens', ligue_1)
Lille = Club('LOSC Lille', ligue_1)
Lorient = Club('FC Lorient', ligue_1)
Lyon = Club('Olympique Lyon', ligue_1)
Marseille = Club('Olympique Marseille', ligue_1)
Monaco = Club('AS Monaco', ligue_1)
Montpellier = Club('Montpellier HSC', ligue_1)
Nantes = Club('FC Nantes', ligue_1)
Nice = Club('OGC Nice', ligue_1)
Paris = Club('Paris Saint-Germain', ligue_1)
Reims = Club('Stade Reims', ligue_1)
Rennes = Club( 'Stade Rennais FC', ligue_1)
Strasbourg = Club('RC Strasbourg Alsace', ligue_1)
Toulouse = Club('FC Toulouse', ligue_1)
Troyes = Club('ESTAC Troyes', ligue_1)


#premier league
premier_league = League('premier-league','GB1',2022,20,'EPL')

Arsenal = Club('Arsenal FC',premier_league)
Tottenham = Club('Tottenham Hotspur',premier_league)
Bournemouth = Club('AFC Bournemouth',premier_league)
Brentford = Club('Brentford FC',premier_league)
Crystal_palace = Club('Crystal Palace',premier_league)
Chelsea = Club('Chelsea FC',premier_league)
Fulham = Club('Fulham FC',premier_league)
Newcastle = Club( 'Newcastle United',premier_league)
Liverpool = Club('Liverpool FC',premier_league)
Brighton = Club('Brighton & Hove Albion',premier_league)
Southampton = Club('Southampton FC',premier_league)
Everton = Club('Everton FC',premier_league)
West_Ham = Club('West Ham United',premier_league)
Wolverhampton = Club('Wolverhampton Wanderers',premier_league)
Manchester_city = Club('Manchester City',premier_league)
Manchester_united = Club('Manchester United',premier_league)
Leeds = Club('Leeds United',premier_league)
Aston_villa = Club('Aston Villa',premier_league)
Leicester = Club('Leicester City',premier_league)
Nottingham = Club('Nottingham Forest',premier_league)


#primera division
primera_division = League('primera-division','ES1',2022,20,'La_liga')

Almeria = Club('UD Almería',primera_division)
Athletico_Bilbao = Club('Athletic Bilbao',primera_division)
Athletico_Madrid = Club('Atlético de Madrid',primera_division)
Barcelona = Club('FC Barcelona',primera_division)
Cadiz = Club('Cádiz CF',primera_division)
Celta_Vigo = Club('Celta de Vigo',primera_division)
Elche = Club('Elche CF',primera_division)
Espagnol_barcelona = Club('RCD Espanyol Barcelona',primera_division)
Getafe = Club('Getafe CF',primera_division)
Girona = Club('Girona FC',primera_division)
Mallorca = Club('RCD Mallorca',primera_division)
Osasuna = Club('CA Osasuna',primera_division)
Rayo_vallecano = Club('Rayo Vallecano',primera_division)
Real_betis = Club('Real Betis Balompié',primera_division)
Real_madrid = Club('Real Madrid',primera_division)
Real_sociedad= Club('Real Sociedad',primera_division)
Real_valladolid = Club('Real Valladolid CF',primera_division)
Valencia = Club('Valencia CF',primera_division)
Villareal = Club('Villarreal CF',primera_division)
Sevilla = Club('Sevilla FC',primera_division)

#serie A
serie_a = League('serie-a','IT1',2022,20,'Serie_A')

Atalanta = Club('Atalanta BC',serie_a)
Bologna = Club('Bologna FC 1909',serie_a)
Cremonese = Club('US Cremonese',serie_a)
Empoli = Club('FC Empoli',serie_a)
Fiorentina = Club('ACF Fiorentina',serie_a)
Hellas_verona = Club('Hellas Verona',serie_a)
Inter_milan = Club('Inter Milan',serie_a)
Juventus = Club('Juventus FC',serie_a)
Lazio = Club('SS Lazio',serie_a)
Lecce = Club('US Lecce',serie_a)
Milan = Club('AC Milan',serie_a)
Monza = Club('AC Monza',serie_a)
Napoli = Club('SSC Napoli',serie_a)
Roma = Club('AS Roma',serie_a)
Salernitana = Club('US Salernitana 1919',serie_a)
Sampdoria = Club('UC Sampdoria',serie_a)
Sassuolo = Club('US Sassuolo',serie_a)
Spezia = Club('Spezia Calcio',serie_a)
Torino = Club('Torino FC',serie_a)
Udinese = Club('Udinese Calcio',serie_a)


#bundesliga
bundesliga = League('bundesliga','L1',2022,18,'Bundesliga')

Ausbourg = Club('FC Augsburg',bundesliga)
Bayer_Lerverkusen = Club('Bayer 04 Leverkusen',bundesliga)
Bayern_Munich = Club('Bayern Munich',bundesliga)
Bochum = Club('VfL Bochum',bundesliga)
Borussia_Dortmund = Club('Borussia Dortmund',bundesliga)
Borussia_Möchengladbach = Club('Borussia Mönchengladbach',bundesliga)
Frankfurt = Club('Eintracht Frankfurt',bundesliga)
Freiburg = Club('SC Freiburg',bundesliga)
Hertha = Club('Hertha BSC',bundesliga)
Hoffenheim = Club( 'TSG 1899 Hoffenheim',bundesliga)
Köln = Club('1. FC Köln',bundesliga)
Leipzig = Club('RB Leipzig',bundesliga)
Mainz = Club('1.FSV Mainz 05',bundesliga)
Shalke = Club('FC Schalke 04',bundesliga)
Stuttgart = Club('VfB Stuttgart',bundesliga)
Union_berlin = Club('1.FC Union Berlin',bundesliga)
Werder_Bremen = Club('SV Werder Bremen',bundesliga)
Wolsburg = Club('VfL Wolfsburg',bundesliga)
